### ISSUE TITLE
Was working but after a day not displaying anything

### ISSUE THREAD

**Issue by ghost** [kjb085/MMM-Reddit#26]
tried to re download, was working for a day now its not, only displaying headline

**Comment by ghost** [comment]
"Uncaught (in promise) Error: Could not instantiate: ProductRegistryImpl.Registry", source: devtools://devtools/bundled/shell.js (109)

**Comment by ghost** [comment]
{
			
			module: "MMM-Reddit",
			position: "top_left",
				config: {
				subreddit: ['television', 'science', 'headlines'],
				headerType: 'chained',
				displayType: 'headlines',
				count: 12,
				show: 4,
				rotateinterval: 30,				
				width: 500,
				showScore: false,
				showSubreddit: true,
				colorText: false,
				showThumbnail: false,
			}
		},

**Comment by JoshuaShelswell** [comment]
figured it out, was a custom.css setting i had, thankyou

**Comment by JoshuaShelswell** [comment]
Apparently the width was the wrong format your defaults need to be changed width: "500px",

**Comment by JoshuaShelswell** [comment]
i figured it out, its something to do with the way i set up my config, its working now but with your earthporn config

**Comment by ghost** [comment]
not sure what i did but i used the earthporn config and put in everything down to show and now its working, sweet

**Comment by ghost** [comment]
seems to be very picky with the count/show amounts cant do any higher than 4/12 and that randomly works and doesnt i was getting this error from my log but its gone now

[2020-12-18 20:49:18.577] [ERROR]  TypeError: Cannot read property 'width' of undefined
    at Class.getAllImages (/home/pi/MagicMirror/modules/MMM-Reddit/node_helper.js:229:38)
    at Class.getImageUrl (/home/pi/MagicMirror/modules/MMM-Reddit/node_helper.js:178:34)
    at /home/pi/MagicMirror/modules/MMM-Reddit/node_helper.js:76:45
    at Array.forEach (<anonymous>)
    at Request._callback (/home/pi/MagicMirror/modules/MMM-Reddit/node_helper.js:70:44)
    at Request.self.callback (/home/pi/MagicMirror/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (/home/pi/MagicMirror/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (/home/pi/MagicMirror/node_modules/request/request.js:1076:12)
[2020-12-18 20:49:18.587] [ERROR]  MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[2020-12-18 20:49:18.596] [ERROR]  If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
[27670:1218/205228.964616:ERROR:CONSOLE(24)] "Empty response arrived for script 'devtools://devtools/remote/serve_file/@35495e19901729e3202257e990a85b3db05fbbef/product_registry_impl/product_registry_impl_module.js'", source: devtools://devtools/bundled/shell.js (24)
[27670:1218/205229.234087:ERROR:CONSOLE(109)] "Uncaught (in promise) Error: Could not instantiate: ProductRegistryImpl.Registry", source: devtools://devtools/bundled/shell.js (109

**Comment by ghost** [comment]
well its working, for now, this is the config, im still getting that error in my logs though

		{
			module: "MMM-Reddit",
			position: "top_left",
			config: {
				subreddit: ['television', 'science', 'nottheonion', 'news'],
				headerType: 'chained',
				displayType: 'headlines',
				imageQuality: 'mid',
				count: 12,
				show: 4,
				width: 500,
				showAll: true,
			}
		},

**Comment by JoshuaShelswell** [comment]
found this also
[2020-12-18 20:55:35.805] [ERROR]  [31mWARNING! Could not validate config file. Starting with default configuration. Please correct syntax errors at or above this line: /home/pi/MagicMirror/config/config.js:735[39m
[31m					subreddit: {'television', 'science', 'headlines'},[39m
[31m					                        ^[39m

funny it says this because im using [] not {}
