### ISSUE TITLE
Electron Issue

### ISSUE THREAD

**Issue by Dresch360** [kjb085/MMM-Reddit#36]
Thank you for building this amazing module!

I recently upgraded to MM 2.20.0 and am now getting the old "Electron Error" when MM loads.

Here is the error and any help would be greatly appreciated!

pm ERR! code 1
npm ERR! path /home/pi/MagicMirror/modules/MMM-Reddit/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh /tmp/postinstall-83c677c7.sh
npm ERR! Building: /usr/bin/node /home/pi/MagicMirror/modules/MMM-Reddit/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/usr/bin/node',
npm ERR! gyp verb cli   '/home/pi/MagicMirror/modules/MMM-Reddit/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.7.0
npm ERR! gyp info using node@16.17.1 | linux | arm
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (/home/pi/MagicMirror/modules/MMM-Reddit/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/home/pi/MagicMirror/modules/MMM-Reddit/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/home/pi/MagicMirror/modules/MMM-Reddit/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /home/pi/MagicMirror/modules/MMM-Reddit/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /home/pi/MagicMirror/modules/MMM-Reddit/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /home/pi/MagicMirror/modules/MMM-Reddit/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:206:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (/home/pi/MagicMirror/modules/MMM-Reddit/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/home/pi/MagicMirror/modules/MMM-Reddit/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/home/pi/MagicMirror/modules/MMM-Reddit/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /home/pi/MagicMirror/modules/MMM-Reddit/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /home/pi/MagicMirror/modules/MMM-Reddit/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /home/pi/MagicMirror/modules/MMM-Reddit/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:206:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` succeeded python /usr/bin/python
npm ERR! gyp verb check python version `/usr/bin/python -c "import platform; print(platform.python_version());"` returned: "3.9.2\n"
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: Python executable "/usr/bin/python" is v3.9.2, which is not supported by gyp.
npm ERR! gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
npm ERR! gyp ERR! stack     at PythonFinder.failPythonVersion (/home/pi/MagicMirror/modules/MMM-Reddit/node_modules/node-gyp/lib/configure.js:501:19)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/home/pi/MagicMirror/modules/MMM-Reddit/node_modules/node-gyp/lib/configure.js:483:14)
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:392:7)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1093:16)
npm ERR! gyp ERR! stack     at Socket.<anonymous> (node:internal/child_process:451:11)
npm ERR! gyp ERR! stack     at Socket.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at Pipe.<anonymous> (node:net:757:14)
npm ERR! gyp ERR! System Linux 5.15.61-v7l+
npm ERR! gyp ERR! command "/usr/bin/node" "/home/pi/MagicMirror/modules/MMM-Reddit/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /home/pi/MagicMirror/modules/MMM-Reddit/node_modules/node-sass
npm ERR! gyp ERR! node -v v16.17.1
npm ERR! gyp ERR! node-gyp -v v3.7.0
npm ERR! gyp ERR! not ok 
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2022-09-29T05_07_11_094Z-debug-0.log

**Comment by Dresch360** [comment]
Also tried npm install request as others have indicated, but I'm getting the following errors:
npm ERR! code 1
npm ERR! path /home/pi/MagicMirror/modules/MMM-Reddit/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh /tmp/postinstall-29ada8e0.sh
npm ERR! Building: /usr/bin/node /home/pi/MagicMirror/modules/MMM-Reddit/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/usr/bin/node',
npm ERR! gyp verb cli   '/home/pi/MagicMirror/modules/MMM-Reddit/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.7.0
npm ERR! gyp info using node@16.17.1 | linux | arm
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (/home/pi/MagicMirror/modules/MMM-Reddit/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/home/pi/MagicMirror/modules/MMM-Reddit/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/home/pi/MagicMirror/modules/MMM-Reddit/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /home/pi/MagicMirror/modules/MMM-Reddit/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /home/pi/MagicMirror/modules/MMM-Reddit/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /home/pi/MagicMirror/modules/MMM-Reddit/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:206:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (/home/pi/MagicMirror/modules/MMM-Reddit/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/home/pi/MagicMirror/modules/MMM-Reddit/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/home/pi/MagicMirror/modules/MMM-Reddit/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /home/pi/MagicMirror/modules/MMM-Reddit/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /home/pi/MagicMirror/modules/MMM-Reddit/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /home/pi/MagicMirror/modules/MMM-Reddit/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:206:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` succeeded python /usr/bin/python
npm ERR! gyp verb check python version `/usr/bin/python -c "import platform; print(platform.python_version());"` returned: "3.9.2\n"
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: Python executable "/usr/bin/python" is v3.9.2, which is not supported by gyp.
npm ERR! gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
npm ERR! gyp ERR! stack     at PythonFinder.failPythonVersion (/home/pi/MagicMirror/modules/MMM-Reddit/node_modules/node-gyp/lib/configure.js:501:19)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/home/pi/MagicMirror/modules/MMM-Reddit/node_modules/node-gyp/lib/configure.js:483:14)
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:392:7)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1093:16)
npm ERR! gyp ERR! stack     at Socket.<anonymous> (node:internal/child_process:451:11)
npm ERR! gyp ERR! stack     at Socket.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at Pipe.<anonymous> (node:net:757:14)
npm ERR! gyp ERR! System Linux 5.15.61-v7l+
npm ERR! gyp ERR! command "/usr/bin/node" "/home/pi/MagicMirror/modules/MMM-Reddit/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /home/pi/MagicMirror/modules/MMM-Reddit/node_modules/node-sass
npm ERR! gyp ERR! node -v v16.17.1
npm ERR! gyp ERR! node-gyp -v v3.7.0
npm ERR! gyp ERR! not ok 
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2022-10-06T00_18_25_082Z-debug-0.log
